[package]
name = "proxy"
version = "0.1.0"
authors = ["remtori <lqvu99@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
http = { path = "../../lib/http" }
utils = { path = "../../lib/utils" }
