[package]
name = "dattach"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = [ "full" ] }
futures = "0.3.17"
tokio-tungstenite = "0.16"
futures-util = "0.3.17"
tungstenite = "0.16.0"
anyhow = "1.0.51"
lazy_static = "1.4.0"
chashmap = "2.2.2"
