[package]
name = "audio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiopus = "0.2"
clap = "2.33"
sfml = { version = "0.16", default-features = false, features = [ "audio" ] }
