[package]
name = "nes"
version = "0.1.0"
authors = ["remtori <lqvu99@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4.0"
ggez = "0.5.1"
utils = { path = "../../lib/utils" }
