[package]
name = "server"
version = "0.1.0"
authors = ["remtori <lqvu99@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
actix = "0.10.0"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.3"

bytes = "0.5.6"

# logger
log = "0.4"
fern = "0.6"

# Date & time lib
chrono = "0.4"
